title: Recreational programming club
description: A safe place to practise programming challenges for people who love problem solving <3
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
